services:
  postgres_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admincvbn
      POSTGRES_PASSWORD: qgHIhuUH
      POSTGRES_DB: audio_notes_saver
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  fastapi_app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres_db
    env_file:
      - .env
    environment:
      # These override values from .env for local compose convenience
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: audio_notes_saver
      DB_USER: admincvbn
      DB_PASSWORD: qgHIhuUH
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data: